import AccountDetailsProvider from "./_components/AccountDetailsContext";
import "./_styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AccountDetailsProvider>
        <body className="flex flex-col justify-center min-h-screen">
          {children}
        </body>
      </AccountDetailsProvider>
    </html>
  );
}
