import localFont from "next/font/local";
<<<<<<< HEAD
import "./_styles/globals.css";
=======
import "./globals.css";
>>>>>>> 387cfe15d010aea626e00b039d3430ccf8b05046

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<<<<<<< HEAD
export default function Home({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* Header */}
        <header className="bg-indigo-600 text-white py-4">
          <h1 className="text-center text-xl font-bold">
            Welcome to IE Banking
          </h1>
        </header>

        {/* Main Content */}
        <main className="flex-grow bg-gray-100 flex items-center justify-center">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-indigo-600 text-white py-2">
          <p className="text-center text-sm">
            &copy; {new Date().getFullYear()} IE Banking. All Rights Reserved.
          </p>
        </footer>
=======

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 387cfe15d010aea626e00b039d3430ccf8b05046
      </body>
    </html>
  );
}
