import localFont from "next/font/local";
import "../_styles/globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  const options = [
    { id: 1, label: "Withdraw Money" },
    { id: 2, label: "Deposit" },
    { id: 3, label: "View Transactions" },
    { id: 4, label: "Transfer Money" },
    { id: 5, label: "Settings" },
  ];

  return (
    <html lang="en">
      <body className="flex flex-row min-h-screen bg-gray-50">
        {/* Left Section */}
        <aside className="w-full md:max-w-xs lg:max-w-sm bg-gradient-to-b from-blue-500 to-blue-700 text-white flex-shrink-0 overflow-auto p-6 shadow-lg">
          <h2 className="text-2xl font-bold mb-4">Welcome, X</h2>
          <p className="text-sm leading-relaxed">
            Account Balance: <span className="font-semibold">$X</span>
          </p>

          <div className="mt-6">
            <ul className="space-y-2">
              {options.map((option) => (
                <li
                  key={option.id}
                  className="p-3 bg-blue-400 hover:bg-blue-500 rounded-lg shadow-md cursor-pointer text-center font-medium"
                >
                  {option.label}
                </li>
              ))}
            </ul>
          </div>
        </aside>

        {/* Main Section */}
        <main className="flex-1 p-4 bg-white overflow-auto">{children}</main>
      </body>
    </html>
  );
}
